# Generated by Django 2.1.7 on 2019-03-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190314_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
